# This file was generated by liblab | https://liblab.com/

from labelkit_app import LabelkitApp, Environment

sdk = LabelkitApp(base_url=Environment.DEFAULT.value)

result = sdk.dataset.list_datasets()

print(result)
