# This file was generated by liblab | https://liblab.com/

from typing import List
from .utils.json_map import JsonMap
from .base import BaseModel


@JsonMap({"dataset_id": "datasetId", "dataset_rows": "datasetRows"})
class AddDataPayload(BaseModel):
    """AddDataPayload

    :param dataset_id: dataset_id, defaults to None
    :type dataset_id: str, optional
    :param dataset_rows: dataset_rows, defaults to None
    :type dataset_rows: List[dict], optional
    """

    def __init__(self, dataset_id: str = None, dataset_rows: List[dict] = None):
        if dataset_id is not None:
            self.dataset_id = dataset_id
        if dataset_rows is not None:
            self.dataset_rows = dataset_rows
