# This file was generated by liblab | https://liblab.com/

from .services.dataset import DatasetService
from .services.experiment import ExperimentService
from .net.environment import Environment


class LabelkitApp:
    def __init__(self, base_url: str = Environment.DEFAULT.value):
        """
        Initializes LabelkitApp the SDK class.
        """
        self.dataset = DatasetService(base_url=base_url)
        self.experiment = ExperimentService(base_url=base_url)

    def set_base_url(self, base_url):
        """
        Sets the base URL for the entire SDK.
        """
        self.dataset.set_base_url(base_url)
        self.experiment.set_base_url(base_url)

        return self


# c029837e0e474b76bc487506e8799df5e3335891efe4fb02bda7a1441840310c
